name: kradioplayer
description: Awesome Online Radio Player
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  http: ^0.12.0
  equatable: ^1.1.1
  just_audio: ^0.1.9
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0
  network_image_mock: ^1.0.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true
